config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post 'auth_user' => 'authentication#authenticate_user'
  root to: 'home#index'
  post 'bot_actions/process_user_input'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bot_action.rb
class BotAction < ApplicationRecord
  include Rails.application.routes.url_helpers

  belongs_to :user
  validates_presence_of :user_input, message: "ты хотел что-то сказать"
  validates_length_of :user_input, minimum: 2, maximum: 200, message: "accepts only 2 - 200" 
  before_save :strip_user_input

TRAINING_DATA = YAML.load_file('config/chatbot/training.yml') 
EVENTS_ARRAY = {"events" => ["да", "ок", "давай", "события", "событие", "ивенты", "ивент", "интересное", "семинары", "семинар", "концерты", "концерт", "уроки", "урок", "лекции", "фильмы", "куда"]}


#1
def process_input(user_input)
  user_input_tokens = clean_user_input(user_input)
  common_array = user_input_tokens & EVENTS_ARRAY["events"]  #Intersection of both arrays
  common_word = common_array.present? ? EVENTS_ARRAY.keys[0] : "classification_failed"
  send("#{common_word}_enquiry", user_input_tokens)
end

def classification_failed_enquiry(*args)
    self.update_attribute(:bot_response, error_response)
    return false
end

def self.greeting(id)
  BotAction.create(bot_response: "Привет! Меня зовут Хлои. Я умею находить интересные события рядом. Что тебе интересно?", user_id: id, created_at: Time.now, updated_at: Time.now)
end

#3 nbayes iterates
 def nbayes_classification(user_input_tokens, method_name)
    nbayes = NBayes::Base.new(binarized: true)             #
    TRAINING_DATA[method_name.to_s].each do |key, value|   #getting the inner hash, ex: 'new_laptop_enquiry' hash
      category = key                                       #assigning key as category (class), ex: 'new_laptop_enquiry'
      #puts "\n\nCategory: #{category.inspect}\n\n"
      value.each do |str|
        #puts "\n\nString: #{str.inspect}\n\n"
        nbayes.train(str.split(/\s+/), category)           #Training the nbayes object, with each string under 'new_laptop_enquiry' class
      end
    end
 
    nbayes.assume_uniform = true                           #
    result = nbayes.classify(user_input_tokens)            #classifying the input form user 
    #nbayes.dump('config/rembot/dump.yml')                 #dump of trained data, for us to observe how the classification is done
    result.each do |k, v|
      puts "\n#{(v * 100)} => #{k}\n"                      #display of classified log probabilities for each category
    end
    result.max_class                                       #final classified category, ex: 'new_laptop_enquiry'
end



#classifications related to events
#2 we understand the query is about the event
  def events_enquiry(user_input_tokens)
    send(nbayes_classification(user_input_tokens, __method__))
  end

#4
  def tomorrow_event_enquiry(*args)
    self.update_attribute(:bot_response, "Интересные события на завтра:")
    #some action triggers
    new_polymorphic_path('event')
  end
 
  def event_index_enquiry(*args)
    # self.update_attribute(:bot_response, "Вот все события сегодня в городе:")
    mix = URI.parse("https://api.timepad.ru/v1/events.json").read
    mix = ActiveSupport::JSON.decode(mix)["values"]
    self.update_attribute(:bot_response, mix)
    #some action triggers
    polymorphic_path('events')
  end
 
  def more_event_enquiry(*args)
    laptop_count = Event.all.count
    self.update_attribute(:bot_response, "There are #{event_count} events in total")
    #some action triggers
    return false
  end
 
private

def error_response
    ["Сори, не поняла, бывает.. давай еще разок",
     "Ты по-русски можешь сказать?... не понятно", 
     "Так... давай еще раз, но внятнее..",
     "Перефразируй, братюня..,
     Давай потолкуем.. давай потолкуем.. Короче не поняла я.."].sample
  end
 
def strip_user_input
    self.user_input = self.user_input.squish
end

def clean_user_input(user_input)
    # rm_spl_chars = user_input.downcase.gsub(/[^a-zA-Z0-9-#\s]/, '')
    # rm_spl_chars.split(/\s+/)
    rm_spl_chars = user_input.downcase.split(/[^[:word:]]+/)
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :bot_actions
    #has_many :interests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  attr_reader :current_user
  #protect_from_forgery with: :exception
  before_action :new_bot_action

  protected

 def new_bot_action
    if current_user.present?
      @bot_action = BotAction.new
      @bot_chat = current_user.bot_actions.last(2)
      	if @bot_chat.length < 1
			@bot_chat << BotAction.greeting(current_user.id)
			#current_user.bot_actions.create(bot_response: "Привет! Меня зовут Хлои. Показать тебе интересные события рядом?", created_at: Time.now)
		end
    end
end


  def authenticate_request!
    unless user_id_in_token?
      render json: { errors: ['Not Authenticated'] }, status: :unauthorized
      return
    end
    @current_user = User.find(auth_token[:user_id])
  rescue JWT::VerificationError, JWT::DecodeError
    render json: { errors: ['Not Authenticated'] }, status: :unauthorized
  end

  private
  def http_token
      @http_token ||= if request.headers['Authorization'].present?
        request.headers['Authorization'].split(' ').last
      end
  end

  def auth_token
    @auth_token ||= JsonWebToken.decode(http_token)
  end

  def user_id_in_token?
    http_token && auth_token && auth_token[:user_id].to_i
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def authenticate_user
    user = User.find_for_database_authentication(email: params[:email])
    if user.valid_password?(params[:password])
      render json: payload(user)
    else
      render json: {errors: ['Invalid Username/Password']}, status: :unauthorized
    end
  end

  private

  def payload(user)
    return nil unless user and user.id
    {
      auth_token: JsonWebToken.encode({user_id: user.id}),
      user: {id: user.id, email: user.email}
    }
  end
end

app/controllers/bot_actions_controller.rb
class BotActionsController < ApplicationController
  def process_user_input
    @bot_action = current_user.bot_actions.build(bot_action_params)
    if @bot_action.save
      @return_user_input = @bot_action.user_input
      computed_path = @bot_action.process_input(@return_user_input)
      @return_bot_response = @bot_action.bot_response
      #puts "\n\nCOMPUTED PATH: #{computed_path.inspect}\n\n"
      if computed_path.present?
        #redirection to computed_path
        render js: "window.location = '#{computed_path}'"
      end
    end
    respond_to do |format|
      format.js
      #format.js { render :json { :only => :name }.to_json }
      #json_response(@bot_action)
    end
  end
 
  private
 
  def bot_action_params
    params.require(:bot_action).permit(:user_input, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_request!

  def index
    render json: {'logged_in' => true}
  end
end

app/views/bot_actions/_bot_response.html.haml
.chat-body.clearfix
  .header
    %small.text-muted
      %span.glyphicon.glyphicon-time
      #{time_ago_in_words(bot_action.updated_at)} ago
    %strong.pull-right.primary-font Bot
  %p= return_bot_response

app/views/bot_actions/_user_input.html.haml
.chat-body.clearfix
  .header
    %strong.primary-font Me
    %small.pull-right.text-muted
      %span.glyphicon.glyphicon-time
      #{time_ago_in_words(bot_action.created_at)} ago
  %p= return_user_input

app/views/bot_actions/process_user_input.js.haml
- if @return_user_input.present? && @return_bot_response.present? && @bot_action.errors.blank?
  $(".chat").append("#{escape_javascript("#{render partial: 'bot_actions/user_input', locals: { return_user_input: @return_user_input, bot_action: @bot_action }}").html_safe}");
  $(".chat").append("#{escape_javascript("#{render partial: 'bot_actions/bot_response', locals: { return_bot_response: @return_bot_response, bot_action: @bot_action }}").html_safe}");
$(".panel-body").animate({ scrollTop: $(".panel-body")[0].scrollHeight}, 0);

app/views/home/index.html.haml
- if current_user
	%h3 Welcome to Ginger

- else
	%h1 Sign up to reach Ginger

app/views/layouts/_chat_bot.html.haml
.container
  .row
    .col-md-5
      .panel.panel-primary
        .panel-body
          %ul.chat
            - bot_chat.each do |chat|
              .chat-body.clearfix
                .header
                  %strong.primary-font Me
                  %small.pull-right.text-muted
                    %span.glyphicon.glyphicon-time
                    #{time_ago_in_words(chat.created_at)} ago
                %p= chat.user_input
              .chat-body.clearfix
                .header
                  %small.text-muted
                    %span.glyphicon.glyphicon-time
                    #{time_ago_in_words(chat.updated_at)} ago
                  %strong.pull-right.primary-font Bot
                %p= chat.bot_response
        .panel-footer
          = form_for bot_action, url: bot_actions_process_user_input_path, remote: true do |f|
            .input-group
              = f.text_field :user_input, autocomplete: 'off', class: 'form-control input-sm', id: 'btn-input', placeholder: 'Type your message here...'
              %span.input-group-btn
                = f.submit 'send', class: 'btn btn-sm', id: 'btn-chat'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title ChatBot
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
  .container
    - if user_signed_in?
      .navbar.navbar-text.pull-right
        Logged in as
        %strong
          = current_user.email
        = link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link'
        |
        = link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'
      .navbar.navbar-text.pull-left
        = link_to 'Home', root_path, class: 'navbar-link'
        / |
        / = link_to 'Phones', phones_path, class: 'navbar-link'
        / |
        / = link_to 'Televisions', televisions_path, class: 'navbar-link'
        / |
        / = link_to 'Laptops', laptops_path, class: 'navbar-link'
    - else
      .navbar.navbar-text.pull-right
        = link_to "Sign up", new_user_registration_path, class: 'navbar-link'
        |
        = link_to "Login", new_user_session_path, class: 'navbar-link'
  .container
    .row
      .col-xs-6
        = yield
      .col-xs-0
        - if current_user.present?
          = render 'layouts/chat_bot', bot_action: @bot_action, bot_chat: @bot_chat

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>